import "./globals.css";
import styles from "./layout.module.css";

import { Header, Sidebar } from "./../components";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--inter-font",
});

export const metadata: Metadata = {
  title: "Ask developers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.wrapper}`}>
        <Header />
        <Sidebar />
        {children}
      </body>
    </html>
  );
}
